spring:
  profiles:
    active: secret

---
spring:
  profiles: secret

logging:
  config: classpath:log4j2-secret.xml

---

spring:
  profiles: dev


logging:
  config: classpath:log4j2-dev.xml



---
spring:
  profiles: prod


logging:
  config: classpath:log4j2-prod.xml
